version: "3"

services:
  vit497_mq11_front:
    build:
      context: ./front
    container_name: vit497_mq11_front
    command: serve -s build -l 31002
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
